"""updated bibliography

Revision ID: 8e80ef3c8304
Revises: 
Create Date: 2023-12-14 14:29:05.799056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e80ef3c8304'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bibliographies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abbreviation', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('author', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=True))
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bibliographies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('comment')
        batch_op.drop_column('language')
        batch_op.drop_column('location')
        batch_op.drop_column('year')
        batch_op.drop_column('publisher')
        batch_op.drop_column('author')
        batch_op.drop_column('abbreviation')

    # ### end Alembic commands ###
